### PR TITLE
Getting rid of lambda funcs

### PR DESCRIPTION
**Pull request by cversteeg**
Getting rid of lambda functions in environment, muscle, and skeleton.py files. This allows for these objects to be serialized in Pickle.

All provided notebooks work without issue and pickling the arm26 model works as expected.

### CODE REVIEW

**Comment by JonathanAMichaels** [comment]
Wait for real? So, with this pull request the entire model is JSON serializable and can be saved and loaded directly? I'd never found a way to make that possible.

**Comment by paulgribble** [comment]
that would be pretty sweet wouldn't it

**Comment by cversteeg** [comment]
I believe so; I haven't done a huge amount of testing, but I am able to pickle the effector built in example notebook 1, unpickle it and then integrate with Runge-Kutta without any issues.

I give credit to ChatGPT.
image

**Comment by OlivierCodol** [comment]
Merged. This change has good potential to fix some pre-existing issues with no real drawback. It also aligns with PEP8 recommendations on lambda function usage:

https://peps.python.org/pep-0008/#programming-recommendations

**Pull request merged**
